### ISSUE TITLE
How to save or retrieve a user purchase?

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [arsamme/flutter_cafebazaar_auth#1]
Hello and thanks for your great work here. 

Is there any way to save the user purchases in their profile so whenever they uninstalled and installed the app again, we can unlock the purchased parts of the app?
The only methods I found in the [README](https://github.com/arsamme/flutter_cafebazaar_auth#in-app-storage) file you've provided was:

` var savedData = await CafeBazaarAuth.saveData("My String Data");`
` var savedData = await CafeBazaarAuth.savedData;`

but I dont really get how to work with it.
Any approach would be appreciated.

**Comment by arsamme** [comment]
Hello,
Bazaar only supports saving single string, so you can save your data as string in format you like(i.e. Json).
